# Reviewed legacy Dialyzer baseline. Entries are location-specific and CI checks
# for unused filters, so fixed warnings must be removed and new warnings fail.
[
  {"lib/mix/tasks/selecto.bench.ex", :no_return, {37, 7}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {64, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {94, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {106, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {128, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {136, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :no_return, {170, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :call, {175, 25}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {239, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {256, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {260, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {264, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {305, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {312, 8}},
  {"lib/mix/tasks/selecto.bench.ex", :unused_fun, {359, 8}},
  {"lib/selecto.ex", :invalid_contract, 304},
  {"lib/selecto.ex", :no_return, {261, 7}},
  {"lib/selecto.ex", :call, {1587, 35}},
  {"lib/selecto.ex", :no_return, {2404, 7}},
  {"lib/selecto.ex", :call, {2410, 21}},
  {"lib/selecto.ex", :no_return, {2452, 7}},
  {"lib/selecto.ex", :call, {2458, 21}},
  {"lib/selecto/advanced/cte.ex", :call_without_opaque, {376, 20}},
  {"lib/selecto/advanced/cte.ex", :call_without_opaque, {386, 23}},
  {"lib/selecto/builder/cte.ex", :unused_fun, 315},
  {"lib/selecto/builder/cte.ex", :no_return, {54, 7}},
  {"lib/selecto/builder/cte.ex", :no_return, {120, 8}},
  {"lib/selecto/builder/cte.ex", :call, {125, 35}},
  {"lib/selecto/builder/cte.ex", :call, {155, 50}},
  {"lib/selecto/builder/cte.ex", :unused_fun, {319, 8}},
  {"lib/selecto/builder/retarget.ex", :invalid_contract, 14},
  {"lib/selecto/configuration.ex", :invalid_contract, 168},
  {"lib/selecto/configuration.ex", :no_return, {169, 7}},
  {"lib/selecto/diagnostics.ex", :pattern_match_cov, {123, 8}},
  {"lib/selecto/diagnostics.ex", :pattern_match_cov, {124, 8}},
  {"lib/selecto/domain/choices.ex", :guard_fail, {706, 29}},
  {"lib/selecto/domain/choices.ex", :pattern_match_cov, {708, 8}},
  {"lib/selecto/domain_validator.ex", :pattern_match, 1},
  {"lib/selecto/ecto_adapter.ex", :no_return, {64, 7}},
  {"lib/selecto/ecto_adapter.ex", :call, {68, 23}},
  {"lib/selecto/executor.ex", :pattern_match_cov, {793, 8}},
  {"lib/selecto/executor.ex", :guard_fail, {804, 38}},
  {"lib/selecto/expr.ex", :invalid_contract, 197},
  {"lib/selecto/expr.ex", :invalid_contract, 201},
  {"lib/selecto/expr.ex", :no_return, {198, 7}},
  {"lib/selecto/expr.ex", :call, {198, 26}},
  {"lib/selecto/expr.ex", :no_return, {202, 7}},
  {"lib/selecto/expr.ex", :call, {202, 28}},
  {"lib/selecto/field_resolver/parameterized_parser.ex", :pattern_match, {157, 8}},
  {"lib/selecto/fields.ex", :invalid_contract, 251},
  {"lib/selecto/jsonb.ex", :pattern_match_cov, {99, 8}},
  {"lib/selecto/livebook.ex", :pattern_match, {40, 13}},
  {"lib/selecto/output/transformers/json.ex", :call, {295, 17}},
  {"lib/selecto/performance/query_cache.ex", :pattern_match_cov, {516, 8}},
  {"lib/selecto/query_validator.ex", :call, {604, 33}},
  {"lib/selecto/query_validator.ex", :pattern_match_cov, {666, 16}},
  {"lib/selecto/schema/column.ex", :guard_fail, 171},
  {"lib/selecto/schema/column.ex", :guard_fail, 172},
  {"lib/selecto/subselect.ex", :guard_fail, {412, 48}},
  {"lib/selecto/text_search.ex", :pattern_match_cov, {329, 8}},
  {"lib/selecto/verification/governed_query_composition.ex", :no_return, {61, 7}},
  {"lib/selecto/verification/governed_query_composition.ex", :no_return, {66, 7}},
  {"lib/selecto/verification/governed_query_composition.ex", :no_return, {73, 8}},
  {"lib/selecto/verification/governed_query_composition.ex", :no_return, {209, 54}},
  {"lib/selecto/verification/governed_query_composition.ex", :call, {224, 39}},
  {"lib/selecto/verification/governed_query_composition.ex", :pattern_match, {314, 58}},
  {"lib/selecto/verification/governed_query_composition.ex", :no_return, {452, 8}},
  {"lib/selecto/verification/governed_query_composition.ex", :no_return, {454, 8}},
  {"lib/selecto/verification/governed_query_composition.ex", :call, {457, 5}},
  {"lib/selecto/verification/governed_query_composition.ex", :unused_fun, {463, 8}},
  {"lib/selecto/verification/governed_query_composition.ex", :no_return, {532, 8}},
  {"lib/selecto/verification/query_safety.ex", :no_return, {54, 8}},
  {"lib/selecto/verification/query_safety.ex", :no_return, {35, 5}},
  {"lib/selecto/verification/query_safety.ex", :call, {57, 10}},
  {"lib/selecto/verification/query_safety.ex", :unused_fun, {163, 8}},
  {"lib/selecto/verification/query_safety.ex", :unused_fun, {194, 8}},
  {"lib/selecto/verification/query_safety.ex", :unused_fun, {207, 8}},
  {"lib/selecto/write/adapter_conformance.ex", :pattern_match_cov, {121, 8}}
]
